### ISSUE TITLE
When you scroll down on main page, then press Begin Sharing

### ISSUE THREAD

**Issue by jnayak1** [Tav0/OSF_meetings_ember#56]
When you scroll down on main page, then press Begin Sharing, the page moves down past where it should.

**Comment by TomHeatwole** [comment]
@jnayak1, I'm having trouble reproducing this issue. Is it still a problem?

**Comment by jnayak1** [comment]
Yeah sorry about that, I did not at all say what I meant

**Comment by TomHeatwole** [comment]
This is no longer a problem since we no longer allow scrolling on the main page.
